######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 13 23:15:36 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
